name: info_gram
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.6

  # Google Sign-In
  google_sign_in: ^6.2.1

  # WebView for chatbot
  webview_flutter: ^4.5.0

  # Emoji picker for chat
  emoji_selector: ^0.0.4



  # Shared preferences
  shared_preferences: ^2.2.2



  # SVG support
  flutter_svg: ^2.0.1

  # Cupertino icons (optional)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
